//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiJun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programme
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public string StudyOptions { get; set; }
        public string Lengh { get; set; }
        public string Location { get; set; }
        public string Requirement { get; set; }
        public string Level { get; set; }
    
        public virtual Institute Institute { get; set; }
    }
}
